# Pipeline Separado

## Obtendo tabela FUNDAMENTUS

In [ ]:
!pip install requests pandas lxml

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import requests
import pandas as pd
import io

# 1. Configuração da URL e Headers (para imitar um navegador)
url = "https://www.fundamentus.com.br/fii_resultado.php"

# É importante definir o User-Agent para o site não bloquear o script achando que é um robô malicioso
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}

# 2. Fazer a requisição POST (conforme mostrado no seu DevTools)
print("1. Realizando a requisição POST...")
response = requests.post(url, headers=headers)

# Verificação se deu certo (Status 200 OK)
if response.status_code == 200:
    print("   Sucesso! Conteúdo baixado.")

    # Importante: A imagem mostra que o charset é iso-8859-1.
    # Vamos forçar essa codificação para não ter problemas com acentos.
    response.encoding = 'iso-8859-1'

    # 3. Extrair a tabela do HTML usando Pandas
    # O read_html procura por tags <table> e retorna uma lista de DataFrames
    # O parâmetro decimal e thousands ajudam o pandas a entender os números no formato BR
    print("2. Extraindo a tabela...")
    try:
        tabelas = pd.read_html(io.StringIO(response.text), decimal=',', thousands='.')

        # Normalmente a tabela principal é a primeira encontrada (índice 0)
        df = tabelas[0]

        # Visualizar as primeiras linhas para conferência
        print(f"   Tabela encontrada com {len(df)} linhas.")
        # print(df.head())

        # 4. Transformar em CSV
        print("3. Salvando em CSV...")
        # Usamos sep=';' porque no Brasil o Excel usa vírgula para decimais
        # encoding='utf-8-sig' garante que acentos apareçam corretamente no Excel
        df.to_csv('/content/drive/MyDrive/Colab Notebooks/Investimentos/fii_resultado.csv', index=False, sep=',', encoding='utf-8-sig')

        print("   Arquivo 'fii_resultado.csv' criado com sucesso!")

    except Exception as e:
        print(f"   Erro ao processar a tabela: {e}")
else:
    print(f"Erro na requisição. Status Code: {response.status_code}")

1. Realizando a requisição POST...
   Sucesso! Conteúdo baixado.
2. Extraindo a tabela...
   Tabela encontrada com 535 linhas.
3. Salvando em CSV...
   Arquivo 'fii_resultado.csv' criado com sucesso!

In [ ]:
fii_table = pd.read_csv('fii_resultado.csv')
fii_aux = fii_table.copy()

## Visualizando tabela

In [ ]:
fii_table.head(20)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média
0,AAZQ11,Outros,7.94,"13,20%","12,45%",0.92,190856000,359958,0,0.00,0.00,"0,00%","0,00%"
1,ABCP11,Shoppings,74.62,"9,51%","9,83%",0.70,351392000,78610,1,4925.72,610.81,"12,40%","1,31%"
2,AEFI11,Outros,174.90,"8,55%","0,00%",1.75,411893000,0,0,0.00,0.00,"0,00%","0,00%"
3,AFCR11,Multicategoria,103.15,"12,61%","0,00%",1.07,498867000,0,0,0.00,0.00,"0,00%","0,00%"
4,AFHF11,Outros,9.99,"3,93%","5,04%",0.98,49950000,52251,0,0.00,0.00,"0,00%","0,00%"
5,AFHI11,Outros,94.95,"12,97%","12,45%",1.01,432556000,536700,0,0.00,0.00,"0,00%","0,00%"
6,AFOF11,Títulos e Val. Mob.,91.60,"0,82%","0,00%",12.28,1390540000,0,0,0.00,0.00,"0,00%","0,00%"
7,AGCX11,Varejo,1235.50,"0,53%","0,00%",11.57,19291500000,0,82,63941.30,468.90,"0,73%","3,86%"
8,AGRX11,Outros,8.09,"8,51%","11,47%",0.77,144836000,168522,0,0.00,0.00,"0,00%","0,00%"
9,AIEC11,Escritórios,53.26,"8,81%","9,21%",0.66,256979000,437561,2,10122.10,2159.36,"21,33%","0,00%"
10,AJFI11,Shoppings,7.77,"9,69%","9,37%",0.70,245734000,1142050,12,557.77,60.01,"10,76%","3,30%"
11,ALMI11,Escritórios,600.05,"7,38%","7,83%",0.29,66711800,14781,1,1455.95,227.57,"15,63%","46,50%"
12,ALZC11,Outros,7.39,"11,41%","17,17%",0.78,148171000,117394,0,0.00,0.00,"0,00%","0,00%"
13,ALZM11,Títulos e Val. Mob.,6.40,"11,76%","3,90%",0.86,97155500,0,0,0.00,0.00,"0,00%","0,00%"
14,ALZR11,Outros,10.60,"8,66%","9,29%",0.99,1296020000,1550420,19,4582.88,373.15,"8,14%","0,00%"
15,ALZT11,Títulos e Val. Mob.,33.00,"15,52%","1,20%",0.79,16500000,0,0,0.00,0.00,"0,00%","0,00%"
16,ANCR11,Shoppings,333.00,"3,21%","0,59%",2.91,8902770000,5320,8,27218.40,1039.27,"3,82%","4,21%"
17,APTO11,Residencial,8.40,"13,19%","12,79%",0.86,38742700,19643,3,16382.00,1113.82,"6,80%","0,00%"
18,APXM11,Shoppings,72.79,"5,15%","5,48%",0.59,205933000,431120,1,1151.53,157.80,"13,70%","0,00%"
19,ARCT11,Multicategoria,87.13,"-60,77%","0,00%",0.86,368999000,0,12,1100.84,99.19,"9,01%","0,00%"

## Aplicando Correções

In [4]:
# Ler tabela correcoes.csv
correcoes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Investimentos/correcoes.csv')

NameError: name 'pd' is not defined

In [ ]:
for papel in correcoes['Papel']:
    print(f"Papel: {papel}")
    print(f"Correções: {correcoes.loc[correcoes['Papel'] == papel, 'Segmento'].values[0]}")
    print(f"fii_aux: {fii_aux.loc[fii_aux['Papel'] == papel, 'Segmento'].values[0]}")

    # Se o segmento da tabela correcoes for diferente do segmento da tabela fii_aux atualize o segmento de fii_aux
    fii_aux.loc[fii_aux['Papel'] == papel, 'Segmento'] = correcoes.loc[correcoes['Papel'] == papel, 'Segmento'].values[0]

Papel: HABT11
Correções: Cri
fii_aux: Multicategoria
Papel: IRDM11
Correções: Cri
fii_aux: Outros
Papel: OUJP11
Correções: Cri
fii_aux: Multicategoria
Papel: BCRI11
Correções: Cri
fii_aux: Outros
Papel: VCJR11
Correções: Cri
fii_aux: Outros
Papel: ICRI11
Correções: Cri
fii_aux: Outros
Papel: RECR11
Correções: Cri
fii_aux: Multicategoria
Papel: PCIP11
Correções: Cri
fii_aux: Outros
Papel: VGIP11
Correções: Cri
fii_aux: Outros
Papel: HSAF11
Correções: Cri
fii_aux: Outros
Papel: PORD11
Correções: Cri
fii_aux: Multicategoria
Papel: SNCI11
Correções: Cri
fii_aux: Outros
Papel: MCRE11
Correções: Cri
fii_aux: Outros
Papel: CLIN11
Correções: Cri
fii_aux: Outros
Papel: CVBI11
Correções: Cri
fii_aux: Outros
Papel: RZAK11
Correções: Cri
fii_aux: Outros
Papel: KCRE11
Correções: Cri
fii_aux: Multicategoria
Papel: CACR11
Correções: Cri
fii_aux: Multicategoria
Papel: MANA11
Correções: Cri
fii_aux: Outros
Papel: VGIR11
Correções: Cri
fii_aux: Outros
Papel: VVCR11
Correções: Cri
fii_aux: Outros
Papel: XPCI11
Correções: Cri
fii_aux: Outros
Papel: VRTA11
Correções: Cri
fii_aux: Outros
Papel: HGCR11
Correções: Cri
fii_aux: Outros
Papel: RBRY11
Correções: Cri
fii_aux: Outros
Papel: KNUQ11
Correções: Cri
fii_aux: Multicategoria
Papel: RBRR11
Correções: Cri
fii_aux: Outros
Papel: KNHF11
Correções: Cri
fii_aux: Multicategoria
Papel: BTCI11
Correções: Cri
fii_aux: Outros
Papel: MCCI11
Correções: Cri
fii_aux: Outros
Papel: RZLC11
Correções: Cri
fii_aux: Outros
Papel: KNIP11
Correções: Cri
fii_aux: Multicategoria
Papel: KNSC11
Correções: Cri
fii_aux: Multicategoria
Papel: KNCR11
Correções: Cri
fii_aux: Multicategoria
Papel: AFHI11
Correções: Cri
fii_aux: Outros
Papel: KNHY11
Correções: Cri
fii_aux: Multicategoria
Papel: TRBL11
Correções: Logística
fii_aux: Logística
Papel: RBRL11
Correções: Logística
fii_aux: Logística
Papel: MCLO11
Correções: Logística
fii_aux: Logística
Papel: VILG11
Correções: Logística
fii_aux: Logística
Papel: AZPL11
Correções: Logística
fii_aux: Logística
Papel: GGRC11
Correções: Logística
fii_aux: Multicategoria
Papel: HSLG11
Correções: Logística
fii_aux: Logística
Papel: VTLT11
Correções: Logística
fii_aux: Logística
Papel: MXRF11
Correções: Logística
fii_aux: Logística
Papel: KNRI11
Correções: Logística
fii_aux: Multicategoria
Papel: LVBI11
Correções: Logística
fii_aux: Logística
Papel: XPLG11
Correções: Logística
fii_aux: Logística
Papel: BRCO11
Correções: Logística
fii_aux: Logística
Papel: ALZR11
Correções: Logística
fii_aux: Outros
Papel: BTLG11
Correções: Logística
fii_aux: Outros
Papel: HGLG11
Correções: Logística
fii_aux: Multicategoria
Papel: LASC11
Correções: Shoppings
fii_aux: Shoppings
Papel: BBIG11
Correções: Shoppings
fii_aux: Shoppings
Papel: PQDP11
Correções: Shoppings
fii_aux: Shoppings
Papel: PMLL11
Correções: Shoppings
fii_aux: Shoppings
Papel: HSML11
Correções: Shoppings
fii_aux: Shoppings
Papel: MALL11
Correções: Shoppings
fii_aux: Shoppings
Papel: CPSH11
Correções: Shoppings
fii_aux: Shoppings
Papel: VISC11
Correções: Shoppings
fii_aux: Shoppings
Papel: HGBS11
Correções: Shoppings
fii_aux: Shoppings
Papel: XPML11
Correções: Shoppings
fii_aux: Shoppings
Papel: GTWR11
Correções: Escritórios
fii_aux: Escritórios
Papel: HGRE11
Correções: Escritórios
fii_aux: Escritórios
Papel: TEPP11
Correções: Escritórios
fii_aux: Outros
Papel: TVRI11
Correções: Escritórios
fii_aux: Escritórios
Papel: GARE11
Correções: RU
fii_aux: Multicategoria
Papel: HGRU11
Correções: RU
fii_aux: Outros
Papel: CPUR11
Correções: RU
fii_aux: Outros

## Aplicando filtros


*   Liquidez > 200.000
*   Dividend Yield > 7
*   P/VP entre 0,69 e 1,05

In [ ]:
LIQUIDEZ_MIN = 200000
DIVIDEND_YIELD_MIN = 7
P_VP_MIN = 0.69
P_VP_MAX = 1.05

In [ ]:
# Filtra Liquidez > 400000
fii_aux = fii_aux[fii_aux['Liquidez'] > LIQUIDEZ_MIN]

# Transforma coluna Dividend Yield de fii_aux em float
fii_aux['Dividend Yield'] = (
    fii_aux['Dividend Yield']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

# Filtra Dividend Yield > 7%
fii_aux = fii_aux[fii_aux['Dividend Yield'] > DIVIDEND_YIELD_MIN]

# Filtrar 0.69 > P/VP < 1.05
fii_aux = fii_aux[fii_aux['P/VP'] > P_VP_MIN]
fii_aux = fii_aux[fii_aux['P/VP'] < P_VP_MAX]

## Visualizando Tabela

In [ ]:
fii_aux.head(20)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média,Rank DY,Rank PVP,2em1
32,BBIG11,Shoppings,6.94,"19,21%",14.19,0.70,687900000,950688,3,8108.32,524.19,"6,46%","2,50%",27,1,28
10,AJFI11,Shoppings,7.77,"9,69%",9.37,0.70,245734000,1142050,12,557.77,60.01,"10,76%","3,30%",86,2,88
492,VGRI11,Outros,7.53,"15,39%",20.34,0.71,263714000,621755,0,0.00,0.00,"16,66%","0,00%",2,3,5
299,MFII11,Multicategoria,75.50,"3,11%",17.30,0.73,450161000,1302460,3,7842.00,0.00,"0,00%","0,00%",8,4,12
361,PVBI11,Escritórios,78.31,"7,50%",7.61,0.73,2124560000,4801300,7,20749.50,1812.35,"8,73%","16,49%",103,5,108
295,MCLO11,Logística,10.00,"6,98%",8.91,0.73,1246430000,426761,4,1947.87,128.73,"6,61%","0,00%",93,6,99
355,PQDP11,Shoppings,2404.88,"9,74%",9.62,0.73,255528000,590155,1,1898.09,227.36,"11,98%","2,71%",84,7,91
183,HABT11,Multicategoria,70.39,"16,94%",19.36,0.74,572044000,1168010,0,0.00,0.00,"0,00%","0,00%",3,8,11
233,IRDM11,Outros,58.50,"16,47%",17.13,0.74,2202080000,6006290,0,0.00,0.00,"0,00%","0,00%",9,9,18
470,TRBL11,Logística,62.88,"7,71%",11.30,0.74,486634000,599838,6,1417.78,160.89,"11,35%","2,52%",71,10,81
201,HGRE11,Escritórios,118.59,"7,40%",9.80,0.76,1401470000,2187320,13,7583.81,781.28,"10,30%","18,51%",82,11,93
38,BCRI11,Outros,63.74,"13,52%",15.44,0.76,398877000,524422,0,0.00,0.00,"0,00%","0,00%",11,12,23
271,LASC11,Shoppings,98.00,"14,09%",18.36,0.76,288149000,1756640,2,15411.40,1527.27,"9,91%","0,00%",5,13,18
178,GTWR11,Escritórios,76.95,"13,72%",13.19,0.77,923400000,834891,0,0.00,0.00,"14,31%","0,00%",41,14,55
381,RBRF11,Outros,6.65,"17,75%",13.63,0.78,909771000,697808,0,0.00,0.00,"0,00%","0,00%",36,15,51
416,RURA11,Títulos e Val. Mob.,8.16,"13,14%",7.65,0.80,1306410000,1853830,0,0.00,0.00,"0,00%","0,00%",102,16,118
527,XPSF11,Outros,6.29,"13,42%",12.04,0.80,272370000,545229,0,0.00,0.00,"0,00%","0,00%",65,17,82
463,TGAR11,Multicategoria,87.62,"11,10%",13.80,0.81,2065030000,4712620,5,143.30,15.53,"10,84%","0,00%",31,18,49
417,RVBI11,Outros,59.90,"13,05%",14.10,0.81,615533000,931734,0,0.00,0.00,"0,00%","0,00%",28,19,47
275,LIFE11,Residencial,8.11,"14,19%",17.91,0.81,307380000,633378,0,0.00,0.00,"0,00%","0,00%",6,20,26

## Aplicando o Método 2 em 1
* Rank DY + Rank PVP = Rank 2 em 1

In [ ]:
# Ordena a tabela por dividend Yield
fii_aux = fii_aux.sort_values(by='Dividend Yield', ascending=False)

# Cria uma coluna de Rank inteiro
fii_aux['Rank DY'] = range(1, len(fii_aux) + 1)

# Ordena a tabela por P/VP
fii_aux = fii_aux.sort_values(by='P/VP', ascending=True)

# Cria uma coluna de Rank inteiro
fii_aux['Rank PVP'] = range(1, len(fii_aux) + 1)

# Cria a coluna 2em1 que é a soma dos ranks DY e PVP
fii_aux['2em1'] = fii_aux['Rank DY'] + fii_aux['Rank PVP']

fii_aux.to_csv('/content/drive/MyDrive/Colab Notebooks/Investimentos/fii_2em1.csv', index=False, sep=',', encoding='utf-8-sig')

## Visualizando Tabela

In [ ]:
fii_aux.head(20)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média,Rank DY,Rank PVP,2em1
32,BBIG11,Shoppings,6.94,"19,21%",14.19,0.70,687900000,950688,3,8108.32,524.19,"6,46%","2,50%",27,1,28
10,AJFI11,Shoppings,7.77,"9,69%",9.37,0.70,245734000,1142050,12,557.77,60.01,"10,76%","3,30%",86,2,88
492,VGRI11,Outros,7.53,"15,39%",20.34,0.71,263714000,621755,0,0.00,0.00,"16,66%","0,00%",2,3,5
299,MFII11,Multicategoria,75.50,"3,11%",17.30,0.73,450161000,1302460,3,7842.00,0.00,"0,00%","0,00%",8,4,12
361,PVBI11,Escritórios,78.31,"7,50%",7.61,0.73,2124560000,4801300,7,20749.50,1812.35,"8,73%","16,49%",103,5,108
295,MCLO11,Logística,10.00,"6,98%",8.91,0.73,1246430000,426761,4,1947.87,128.73,"6,61%","0,00%",93,6,99
355,PQDP11,Shoppings,2404.88,"9,74%",9.62,0.73,255528000,590155,1,1898.09,227.36,"11,98%","2,71%",84,7,91
183,HABT11,Multicategoria,70.39,"16,94%",19.36,0.74,572044000,1168010,0,0.00,0.00,"0,00%","0,00%",3,8,11
233,IRDM11,Outros,58.50,"16,47%",17.13,0.74,2202080000,6006290,0,0.00,0.00,"0,00%","0,00%",9,9,18
470,TRBL11,Logística,62.88,"7,71%",11.30,0.74,486634000,599838,6,1417.78,160.89,"11,35%","2,52%",71,10,81
201,HGRE11,Escritórios,118.59,"7,40%",9.80,0.76,1401470000,2187320,13,7583.81,781.28,"10,30%","18,51%",82,11,93
38,BCRI11,Outros,63.74,"13,52%",15.44,0.76,398877000,524422,0,0.00,0.00,"0,00%","0,00%",11,12,23
271,LASC11,Shoppings,98.00,"14,09%",18.36,0.76,288149000,1756640,2,15411.40,1527.27,"9,91%","0,00%",5,13,18
178,GTWR11,Escritórios,76.95,"13,72%",13.19,0.77,923400000,834891,0,0.00,0.00,"14,31%","0,00%",41,14,55
381,RBRF11,Outros,6.65,"17,75%",13.63,0.78,909771000,697808,0,0.00,0.00,"0,00%","0,00%",36,15,51
416,RURA11,Títulos e Val. Mob.,8.16,"13,14%",7.65,0.80,1306410000,1853830,0,0.00,0.00,"0,00%","0,00%",102,16,118
527,XPSF11,Outros,6.29,"13,42%",12.04,0.80,272370000,545229,0,0.00,0.00,"0,00%","0,00%",65,17,82
463,TGAR11,Multicategoria,87.62,"11,10%",13.80,0.81,2065030000,4712620,5,143.30,15.53,"10,84%","0,00%",31,18,49
417,RVBI11,Outros,59.90,"13,05%",14.10,0.81,615533000,931734,0,0.00,0.00,"0,00%","0,00%",28,19,47
275,LIFE11,Residencial,8.11,"14,19%",17.91,0.81,307380000,633378,0,0.00,0.00,"0,00%","0,00%",6,20,26

## Visualizando categorias

In [ ]:
# Conta quantos difetens Segmentos existe na coluna Segmento
fii_table['Segmento'].value_counts()

Segmento
Outros                 175
Multicategoria         124
Logística               50
Títulos e Val. Mob.     44
Escritórios             40
Shoppings               39
Residencial             29
Híbrido                  9
Hospital                 8
Lajes Corporativas       7
Varejo                   6
Hotel                    4
Name: count, dtype: int64

In [ ]:
# Conta quantos difetens Segmentos existe na coluna Segmento
fii_aux['Segmento'].value_counts()

Segmento
Cri                    36
Outros                 30
Logística              21
Multicategoria         21
Shoppings              12
Escritórios             5
Títulos e Val. Mob.     5
Residencial             2
RU                      2
Varejo                  1
Hospital                1
Hotel                   1
Name: count, dtype: int64

## Visualizando por Segmentos

In [ ]:
def class_por_segmento(segmento):
    # Cria uma tabela só com Segmento Shoppings
    fii = fii_aux[fii_aux['Segmento'] == segmento]

    # Ordena a tabela por 2em1
    fii = fii.sort_values(by='2em1', ascending=True)
    return fii

In [ ]:
fii_shoppings = class_por_segmento('Shoppings')
fii_shoppings.head(100)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média,Rank DY,Rank PVP,2em1
271,LASC11,Shoppings,98.00,"14,09%",18.36,0.76,288149000,1756640,2,15411.40,1527.27,"9,91%","0,00%",5,20,25
32,BBIG11,Shoppings,6.94,"19,21%",14.19,0.70,687900000,950688,3,8108.32,524.19,"6,46%","2,50%",39,1,40
10,AJFI11,Shoppings,7.77,"9,69%",9.37,0.70,245734000,1142050,12,557.77,60.01,"10,76%","3,30%",115,2,117
355,PQDP11,Shoppings,2404.88,"9,74%",9.62,0.73,255528000,590155,1,1898.09,227.36,"11,98%","2,71%",113,7,120
348,PMLL11,Shoppings,101.18,"14,81%",9.88,0.83,1414710000,4022270,11,3537.76,596.14,"16,85%","3,66%",109,40,149
286,MALL11,Shoppings,100.03,"14,22%",8.91,0.83,1398630000,1520130,11,4650.86,755.88,"16,25%","3,64%",122,41,163
214,HSML11,Shoppings,86.94,"7,36%",9.36,0.84,1854430000,3675370,13,7598.91,818.14,"10,77%","2,57%",116,47,163
94,CPSH11,Shoppings,10.58,"5,44%",11.50,0.90,843224000,4762190,7,786.67,87.08,"11,07%","0,00%",94,77,171
497,VISC11,Shoppings,109.25,"8,67%",8.76,0.89,3149530000,4733090,30,3035.37,290.95,"9,59%","0,00%",124,72,196
194,HGBS11,Shoppings,19.97,"8,01%",9.33,0.92,2578790000,2424660,16,4454.06,435.48,"9,78%","4,50%",117,89,206
525,XPML11,Shoppings,105.98,"9,77%",10.32,0.97,6206990000,11642100,16,6595.20,587.70,"8,91%","4,00%",105,110,215
208,HPDP11,Shoppings,90.00,"7,50%",7.39,0.97,295920000,7087990,1,2196.80,170.04,"7,74%","2,71%",134,109,243

In [ ]:
fii_shoppings = class_por_segmento('Logística')
fii_shoppings.head(100)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média,Rank DY,Rank PVP,2em1
174,GRUL11,Logística,8.20,"15,91%",14.91,0.86,202540000,262990,3,4659.10,774.35,"16,62%","0,00%",23,64,87
523,XPIN11,Logística,76.80,"7,90%",11.77,0.75,549152000,337616,81,2143.71,254.03,"11,85%","6,01%",92,15,107
470,TRBL11,Logística,62.88,"7,71%",11.30,0.74,486634000,599838,6,1417.78,160.89,"11,35%","2,52%",96,12,108
295,MCLO11,Logística,10.00,"6,98%",8.91,0.73,1246430000,426761,4,1947.87,128.73,"6,61%","0,00%",121,9,130
383,RBRL11,Logística,85.21,"9,13%",10.48,0.81,569802000,661062,5,2245.70,268.26,"11,95%","0,00%",104,29,133
27,AZPL11,Logística,7.68,"6,48%",13.01,0.91,321966000,628759,2,492.56,41.09,"8,34%","0,00%",66,81,147
495,VILG11,Logística,92.34,"8,48%",8.78,0.81,1384860000,2364400,15,2435.93,246.00,"10,10%","0,79%",123,30,153
169,GGRC11,Logística,9.90,"6,26%",11.94,0.88,2121070000,7057920,39,2087.49,202.02,"9,68%","0,00%",89,69,158
508,VTLT11,Logística,88.98,"13,31%",13.15,0.96,188193000,546876,1,0.00,109.76,"0,00%","0,00%",61,102,163
213,HSLG11,Logística,91.64,"9,17%",8.75,0.83,1160170000,962306,6,1831.25,165.65,"9,05%","0,00%",125,43,168
141,FIIP11,Logística,170.18,"11,06%",9.78,0.85,157784000,371635,7,2243.53,266.92,"11,90%","0,00%",111,57,168
309,MXRF11,Logística,9.55,"11,19%",13.27,1.01,4176460000,10370100,3,18999.50,0.00,"0,00%","0,00%",55,127,182
285,LVBI11,Logística,106.80,"8,67%",8.66,0.91,1721460000,3424410,11,2811.41,276.21,"9,82%","2,08%",127,79,206
265,KNRI11,Logística,146.45,"8,17%",8.13,0.90,4130480000,5218760,20,5108.22,408.30,"7,99%","0,09%",130,78,208
524,XPLG11,Logística,102.98,"8,97%",9.39,0.97,3210500000,3283260,17,3179.12,268.72,"8,45%","5,06%",114,108,222
14,ALZR11,Logística,10.60,"8,66%",9.29,0.99,1296020000,1550420,19,4582.88,373.15,"8,14%","0,00%",118,115,233
57,BRCO11,Logística,115.91,"7,58%",9.08,0.99,1843560000,3334030,12,3666.14,336.39,"9,18%","7,59%",119,116,235
140,FIIB11,Logística,484.65,"9,46%",10.00,1.02,331985000,348661,11,597.86,63.31,"10,59%","0,00%",107,131,238
69,BTLG11,Logística,103.75,"7,80%",9.06,1.00,5089200000,8457850,5,27663.20,2055.96,"7,43%","0,00%",120,123,243
199,HGLG11,Logística,160.00,"7,78%",8.19,0.99,5406010000,7431240,28,3311.32,277.97,"8,39%","2,91%",129,121,250

In [ ]:
fii_shoppings = class_por_segmento('Escritórios')
fii_shoppings.head(100)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média,Rank DY,Rank PVP,2em1
149,FMOF11,Escritórios,38.88,"11,47%",16.75,0.82,19751400,5038,1,0.00,248.94,"0,00%","4,17%",13,47,60
44,BLCA11,Escritórios,89.57,"7,36%",7.05,0.70,143312000,102521,1,41150.10,3685.39,"8,96%","0,00%",136,2,138
476,TSER11,Escritórios,97.00,"11,45%",13.31,1.00,144094000,0,1,2774.16,256.20,"9,24%","0,00%",61,121,182

In [ ]:
fii_shoppings = class_por_segmento('Residencial')
fii_shoppings.head(100)

,Papel,Segmento,Cotação,FFO Yield,Dividend Yield,P/VP,Valor de Mercado,Liquidez,Qtd de imóveis,Preço do m2,Aluguel por m2,Cap Rate,Vacância Média,Rank DY,Rank PVP,2em1
278,LPLP11,Residencial,260.88,"19,96%",61.47,0.72,193699000,43304,0,0.0,0.00,"0,00%","0,00%",2,9,11
321,OBAL11,Residencial,1095.00,"-2,94%",11.89,0.77,154701000,0,4,16489.4,0.00,"0,00%","0,00%",82,27,109
17,APTO11,Residencial,8.40,"13,19%",12.79,0.86,38742700,19643,3,16382.0,1113.82,"6,80%","0,00%",69,69,138
207,HOSI11,Residencial,84.11,"5,81%",8.86,0.79,48232900,6066,0,0.0,0.00,"0,00%","0,00%",117,34,151
349,PNCR11,Residencial,46.76,"-0,41%",15.94,1.01,23380000,7970,0,0.0,0.00,"0,00%","0,00%",24,130,154
415,RSPD11,Residencial,900.00,"14,80%",14.90,1.02,134110000,4689,1,65695.2,0.00,"0,00%","0,00%",36,136,172
376,RBIR11,Residencial,91.90,"11,89%",13.33,1.00,140480000,242361,1,49839.1,0.00,"0,00%","0,00%",60,120,180
453,SPDE11,Residencial,1266.67,"15,32%",10.98,0.97,115774000,0,0,0.0,0.00,"0,00%","0,00%",94,105,199

# Pipeline Integrado

In [ ]:
import requests
import pandas as pd
import io

LIQUIDEZ_MIN = 200000
DIVIDEND_YIELD_MIN = 7
P_VP_MIN = 0.69
P_VP_MAX = 1.05

# 1. Configuração da URL e Headers (para imitar um navegador)
url = "https://www.fundamentus.com.br/fii_resultado.php"

# É importante definir o User-Agent para o site não bloquear o script achando que é um robô malicioso
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}

# 2. Fazer a requisição POST (conforme mostrado no seu DevTools)
print("1. Realizando a requisição POST...")
response = requests.post(url, headers=headers)

# Verificação se deu certo (Status 200 OK)
if response.status_code == 200:
    print("   Sucesso! Conteúdo baixado.")

    # Importante: A imagem mostra que o charset é iso-8859-1.
    # Vamos forçar essa codificação para não ter problemas com acentos.
    response.encoding = 'iso-8859-1'

    # 3. Extrair a tabela do HTML usando Pandas
    # O read_html procura por tags <table> e retorna uma lista de DataFrames
    # O parâmetro decimal e thousands ajudam o pandas a entender os números no formato BR
    print("2. Extraindo a tabela...")
    try:
        tabelas = pd.read_html(io.StringIO(response.text), decimal=',', thousands='.')

        # Normalmente a tabela principal é a primeira encontrada (índice 0)
        df = tabelas[0]

        # Visualizar as primeiras linhas para conferência
        print(f"   Tabela encontrada com {len(df)} linhas.")
        # print(df.head())

        # 4. Transformar em CSV
        print("3. Salvando em CSV...")
        # Usamos sep=';' porque no Brasil o Excel usa vírgula para decimais
        # encoding='utf-8-sig' garante que acentos apareçam corretamente no Excel
        df.to_csv('fii_resultado.csv', index=False, sep=',', encoding='utf-8-sig')

        print("   Arquivo 'fii_resultado.csv' criado com sucesso!")

    except Exception as e:
        print(f"   Erro ao processar a tabela: {e}")
else:
    print(f"Erro na requisição. Status Code: {response.status_code}")


fii_table = pd.read_csv('fii_resultado.csv')
fii_aux = fii_table.copy()

from google.colab import drive
drive.mount('/content/drive')

# Ler tabela correcoes.csv
correcoes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Investimentos/correcoes.csv')

for papel in correcoes['Papel']:
    # print(f"Papel: {papel}")
    # print(f"Correções: {correcoes.loc[correcoes['Papel'] == papel, 'Segmento'].values[0]}")
    # print(f"fii_aux: {fii_aux.loc[fii_aux['Papel'] == papel, 'Segmento'].values[0]}")

    # Se o segmento da tabela correcoes for diferente do segmento da tabela fii_aux atualize o segmento de fii_aux
    fii_aux.loc[fii_aux['Papel'] == papel, 'Segmento'] = correcoes.loc[correcoes['Papel'] == papel, 'Segmento'].values[0]


# Filtra Liquidez > 400000
fii_aux = fii_aux[fii_aux['Liquidez'] > LIQUIDEZ_MIN]

# Transforma coluna Dividend Yield de fii_aux em float
fii_aux['Dividend Yield'] = (
    fii_aux['Dividend Yield']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

# Filtra Dividend Yield > 7%
fii_aux = fii_aux[fii_aux['Dividend Yield'] > DIVIDEND_YIELD_MIN]

# Filtrar 0.69 > P/VP < 1.05
fii_aux = fii_aux[fii_aux['P/VP'] > P_VP_MIN]
fii_aux = fii_aux[fii_aux['P/VP'] < P_VP_MAX]

# Ordena a tabela por dividend Yield
fii_aux = fii_aux.sort_values(by='Dividend Yield', ascending=False)

# Cria uma coluna de Rank inteiro
fii_aux['Rank DY'] = range(1, len(fii_aux) + 1)

# Ordena a tabela por P/VP
fii_aux = fii_aux.sort_values(by='P/VP', ascending=True)

# Cria uma coluna de Rank inteiro
fii_aux['Rank PVP'] = range(1, len(fii_aux) + 1)

# Cria a coluna 2em1 que é a soma dos ranks DY e PVP
fii_aux['2em1'] = fii_aux['Rank DY'] + fii_aux['Rank PVP']

def class_por_segmento(segmento):
    # Cria uma tabela só com Segmento Shoppings
    fii = fii_aux[fii_aux['Segmento'] == segmento]

    # Ordena a tabela por 2em1
    fii = fii.sort_values(by='2em1', ascending=True)
    return fii

fii_shoppings = class_por_segmento('Shoppings')
fii_shoppings.head(100)